version: '3'
services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  serverless-tutorial-azure:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/home/site/wwwroot
    depends_on:
      - azurite             